# 📄 Resume RAG System for Intelligent Job Matching

This project implements a **Retrieval-Augmented Generation (RAG)** system for semantic resume retrieval and job matching.

## Project Workflow

01. Resume PDFs
02. PDF Text Extraction
03. Intelligent Chunking
04. Metadata Extraction
05. Embedding Generation
06. Chroma Vector Database
07. Semantic Retrieval
08. Hybrid Search (BM25)
09. Candidate Ranking
10. JSON Output

This project uses the following libraries:

| Library | Purpose |
|----------|----------|
| PyMuPDF | Read PDF resumes |
| sentence-transformers | Generate embeddings |
| ChromaDB | Vector database |
| LangChain | Text splitting |
| Rank-BM25 | Keyword search |
| spaCy | Metadata extraction |
| pandas | Data analysis |
| NumPy | Numerical operations |
| tqdm | Progress bars |

These libraries together implement the complete Retrieval-Augmented Generation (RAG) pipeline.

In [1]:
# Uncomment and run only once

!pip install -r ../requirements.txt

Requirement already satisfied: chromadb in d:\github\rag-based-profile-matching\venv\lib\site-packages (from -r ../requirements.txt (line 1)) (1.5.9)
Requirement already satisfied: sentence-transformers in d:\github\rag-based-profile-matching\venv\lib\site-packages (from -r ../requirements.txt (line 2)) (5.7.0)
Requirement already satisfied: langchain in d:\github\rag-based-profile-matching\venv\lib\site-packages (from -r ../requirements.txt (line 3)) (1.3.14)
Requirement already satisfied: langchain-community in d:\github\rag-based-profile-matching\venv\lib\site-packages (from -r ../requirements.txt (line 4)) (0.4.2)
Requirement already satisfied: langchain_openrouter in d:\github\rag-based-profile-matching\venv\lib\site-packages (from -r ../requirements.txt (line 5)) (0.2.7)
Requirement already satisfied: langchain_chroma in d:\github\rag-based-profile-matching\venv\lib\site-packages (from -r ../requirements.txt (line 6)) (1.1.0)
Requirement already satisfied: langchain-text-splitters in d:\github\rag-based-profile-matching\venv\lib\site-packages (from -r ../requirements.txt (line 7)) (1.1.2)
Requirement already satisfied: langchain-huggingface in d:\github\rag-based-profile-matching\venv\lib\site-packages (from -r ../requirements.txt (line 8)) (1.2.2)
Requirement already satisfied: pymupdf in d:\github\rag-based-profile-matching\venv\lib\site-packages (from -r ../requirements.txt (line 9)) (1.28.2)
Requirement already satisfied: rank-bm25 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from -r ../requirements.txt (line 10)) (0.2.2)
Requirement already satisfied: spacy in d:\github\rag-based-profile-matching\venv\lib\site-packages (from -r ../requirements.txt (line 11)) (3.8.13)
Requirement already satisfied: pandas in d:\github\rag-based-profile-matching\venv\lib\site-packages (from -r ../requirements.txt (line 12)) (3.0.5)
Requirement already satisfied: numpy in d:\github\rag-based-profile-matching\venv\lib\site-packages (from -r ../requirements.txt (line 13)) (2.5.1)
Requirement already satisfied: tqdm in d:\github\rag-based-profile-matching\venv\lib\site-packages (from -r ../requirements.txt (line 14)) (4.70.0)
Requirement already satisfied: python-dotenv in d:\github\rag-based-profile-matching\venv\lib\site-packages (from -r ../requirements.txt (line 15)) (1.2.2)
Requirement already satisfied: scikit-learn in d:\github\rag-based-profile-matching\venv\lib\site-packages (from -r ../requirements.txt (line 16)) (1.9.0)
Requirement already satisfied: matplotlib in d:\github\rag-based-profile-matching\venv\lib\site-packages (from -r ../requirements.txt (line 17)) (3.11.1)
Requirement already satisfied: jupyter in d:\github\rag-based-profile-matching\venv\lib\site-packages (from -r ../requirements.txt (line 18)) (1.1.1)
Requirement already satisfied: ipykernel in d:\github\rag-based-profile-matching\venv\lib\site-packages (from -r ../requirements.txt (line 19)) (7.3.0)
Requirement already satisfied: build>=1.0.3 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from chromadb->-r ../requirements.txt (line 1)) (1.5.0)
Requirement already satisfied: pydantic>=2.0 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from chromadb->-r ../requirements.txt (line 1)) (2.12.5)
Requirement already satisfied: pydantic-settings>=2.0 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from chromadb->-r ../requirements.txt (line 1)) (2.15.0)
Requirement already satisfied: pybase64>=1.4.1 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from chromadb->-r ../requirements.txt (line 1)) (1.4.3)
Requirement already satisfied: uvicorn>=0.18.3 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from uvicorn[standard]>=0.18.3->chromadb->-r ../requirements.txt (line 1)) (0.52.1)
Requirement already satisfied: typing-extensions>=4.5.0 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from chromadb->-r ../requirements.txt (line 1)) (4.16.0)
Requirement already satisfied: onnxruntime>=1.14.1 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from chromadb->-r ../requirements.txt (line 1)) (1.28.0)
Requirement already satisfied: opentelemetry-api>=1.2.0 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from chromadb->-r ../requirements.txt (line 1)) (1.44.0)
Requirement already satisfied: opentelemetry-exporter-otlp-proto-grpc>=1.2.0 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from chromadb->-r ../requirements.txt (line 1)) (1.44.0)
Requirement already satisfied: opentelemetry-sdk>=1.2.0 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from chromadb->-r ../requirements.txt (line 1)) (1.44.0)
Requirement already satisfied: tokenizers>=0.13.2 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from chromadb->-r ../requirements.txt (line 1)) (0.22.2)
Requirement already satisfied: pypika>=0.48.9 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from chromadb->-r ../requirements.txt (line 1)) (0.51.1)
Requirement already satisfied: overrides>=7.3.1 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from chromadb->-r ../requirements.txt (line 1)) (7.7.0)
Requirement already satisfied: importlib-resources in d:\github\rag-based-profile-matching\venv\lib\site-packages (from chromadb->-r ../requirements.txt (line 1)) (7.1.0)
Requirement already satisfied: grpcio>=1.58.0 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from chromadb->-r ../requirements.txt (line 1)) (1.83.0)
Requirement already satisfied: bcrypt>=4.0.1 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from chromadb->-r ../requirements.txt (line 1)) (5.0.0)
Requirement already satisfied: typer>=0.9.0 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from chromadb->-r ../requirements.txt (line 1)) (0.27.1)
Requirement already satisfied: kubernetes>=28.1.0 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from chromadb->-r ../requirements.txt (line 1)) (36.0.3)
Requirement already satisfied: tenacity>=8.2.3 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from chromadb->-r ../requirements.txt (line 1)) (9.1.4)
Requirement already satisfied: pyyaml>=6.0.0 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from chromadb->-r ../requirements.txt (line 1)) (6.0.3)
Requirement already satisfied: mmh3>=4.0.1 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from chromadb->-r ../requirements.txt (line 1)) (5.2.1)
Requirement already satisfied: orjson>=3.9.12 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from chromadb->-r ../requirements.txt (line 1)) (3.11.9)
Requirement already satisfied: httpx>=0.27.0 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from chromadb->-r ../requirements.txt (line 1)) (0.28.1)
Requirement already satisfied: rich>=10.11.0 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from chromadb->-r ../requirements.txt (line 1)) (15.0.0)
Requirement already satisfied: jsonschema>=4.19.0 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from chromadb->-r ../requirements.txt (line 1)) (4.26.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from sentence-transformers->-r ../requirements.txt (line 2)) (5.14.1)
Requirement already satisfied: huggingface-hub>=0.23.0 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from sentence-transformers->-r ../requirements.txt (line 2)) (1.27.0)
Requirement already satisfied: torch>=1.11.0 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from sentence-transformers->-r ../requirements.txt (line 2)) (2.13.0)
Requirement already satisfied: scipy>=1.0.0 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from sentence-transformers->-r ../requirements.txt (line 2)) (1.18.0)
Requirement already satisfied: packaging>=20.0 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers->-r ../requirements.txt (line 2)) (26.3)
Requirement already satisfied: regex>=2025.10.22 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers->-r ../requirements.txt (line 2)) (2026.7.19)
Requirement already satisfied: safetensors>=0.8.0 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers->-r ../requirements.txt (line 2)) (0.8.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers->-r ../requirements.txt (line 2)) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers->-r ../requirements.txt (line 2)) (3.32.2)
Requirement already satisfied: fsspec>=2023.5.0 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers->-r ../requirements.txt (line 2)) (2026.7.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers->-r ../requirements.txt (line 2)) (1.6.0)
Requirement already satisfied: colorama in d:\github\rag-based-profile-matching\venv\lib\site-packages (from click<9.0.0,>=8.4.2->huggingface-hub>=0.23.0->sentence-transformers->-r ../requirements.txt (line 2)) (0.4.6)
Requirement already satisfied: anyio in d:\github\rag-based-profile-matching\venv\lib\site-packages (from httpx>=0.27.0->chromadb->-r ../requirements.txt (line 1)) (4.14.2)
Requirement already satisfied: certifi in d:\github\rag-based-profile-matching\venv\lib\site-packages (from httpx>=0.27.0->chromadb->-r ../requirements.txt (line 1)) (2026.7.22)
Requirement already satisfied: httpcore==1.* in d:\github\rag-based-profile-matching\venv\lib\site-packages (from httpx>=0.27.0->chromadb->-r ../requirements.txt (line 1)) (1.0.9)
Requirement already satisfied: idna in d:\github\rag-based-profile-matching\venv\lib\site-packages (from httpx>=0.27.0->chromadb->-r ../requirements.txt (line 1)) (3.18)
Requirement already satisfied: h11>=0.16 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from httpcore==1.*->httpx>=0.27.0->chromadb->-r ../requirements.txt (line 1)) (0.16.0)
Requirement already satisfied: langchain-core<2.0.0,>=1.4.9 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from langchain->-r ../requirements.txt (line 3)) (1.5.3)
Requirement already satisfied: langgraph<1.3.0,>=1.2.5 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from langchain->-r ../requirements.txt (line 3)) (1.2.10)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from langchain-core<2.0.0,>=1.4.9->langchain->-r ../requirements.txt (line 3)) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from langchain-core<2.0.0,>=1.4.9->langchain->-r ../requirements.txt (line 3)) (0.0.18)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from langchain-core<2.0.0,>=1.4.9->langchain->-r ../requirements.txt (line 3)) (0.10.17)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from langchain-core<2.0.0,>=1.4.9->langchain->-r ../requirements.txt (line 3)) (0.17.0)
Requirement already satisfied: jsonpointer>=1.9 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.4.9->langchain->-r ../requirements.txt (line 3)) (3.1.1)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=4.1.0 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from langgraph<1.3.0,>=1.2.5->langchain->-r ../requirements.txt (line 3)) (4.1.1)
Requirement already satisfied: langgraph-prebuilt<1.2.0,>=1.1.0 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from langgraph<1.3.0,>=1.2.5->langchain->-r ../requirements.txt (line 3)) (1.1.0)
Requirement already satisfied: langgraph-sdk<0.5.0,>=0.4.2 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from langgraph<1.3.0,>=1.2.5->langchain->-r ../requirements.txt (line 3)) (0.4.2)
Requirement already satisfied: xxhash>=3.5.0 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from langgraph<1.3.0,>=1.2.5->langchain->-r ../requirements.txt (line 3)) (3.8.1)
Requirement already satisfied: ormsgpack>=1.12.0 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from langgraph-checkpoint<5.0.0,>=4.1.0->langgraph<1.3.0,>=1.2.5->langchain->-r ../requirements.txt (line 3)) (1.12.2)
Requirement already satisfied: websockets<16,>=14 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from langgraph-sdk<0.5.0,>=0.4.2->langgraph<1.3.0,>=1.2.5->langchain->-r ../requirements.txt (line 3)) (15.0.1)
Requirement already satisfied: distro>=1.7.0 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.9->langchain->-r ../requirements.txt (line 3)) (1.9.0)
Requirement already satisfied: requests-toolbelt>=1.0.0 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.9->langchain->-r ../requirements.txt (line 3)) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.9->langchain->-r ../requirements.txt (line 3)) (2.34.2)
Requirement already satisfied: sniffio>=1.1 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.9->langchain->-r ../requirements.txt (line 3)) (1.3.1)
Requirement already satisfied: zstandard>=0.23.0 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.9->langchain->-r ../requirements.txt (line 3)) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from pydantic>=2.0->chromadb->-r ../requirements.txt (line 1)) (0.8.0)
Requirement already satisfied: pydantic-core==2.41.5 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from pydantic>=2.0->chromadb->-r ../requirements.txt (line 1)) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from pydantic>=2.0->chromadb->-r ../requirements.txt (line 1)) (0.4.2)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from langchain-community->-r ../requirements.txt (line 4)) (3.14.3)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from langchain-community->-r ../requirements.txt (line 4)) (0.4.3)
Requirement already satisfied: langchain-classic<2.0.0,>=1.0.7 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from langchain-community->-r ../requirements.txt (line 4)) (1.0.8)
Requirement already satisfied: sqlalchemy<3.0.0,>=1.4.0 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from langchain-community->-r ../requirements.txt (line 4)) (2.0.51)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->-r ../requirements.txt (line 4)) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->-r ../requirements.txt (line 4)) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->-r ../requirements.txt (line 4)) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->-r ../requirements.txt (line 4)) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->-r ../requirements.txt (line 4)) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->-r ../requirements.txt (line 4)) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community->-r ../requirements.txt (line 4)) (1.24.5)
Requirement already satisfied: charset_normalizer<4,>=2 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.9->langchain->-r ../requirements.txt (line 3)) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.26 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.4.9->langchain->-r ../requirements.txt (line 3)) (2.7.0)
Requirement already satisfied: greenlet>=1 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from sqlalchemy<3.0.0,>=1.4.0->langchain-community->-r ../requirements.txt (line 4)) (3.5.4)
Requirement already satisfied: openrouter<1.0.0,>=0.9.2 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from langchain_openrouter->-r ../requirements.txt (line 5)) (0.11.46)
Requirement already satisfied: jsonpath-python>=1.0.6 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from openrouter<1.0.0,>=0.9.2->langchain_openrouter->-r ../requirements.txt (line 5)) (1.1.6)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from spacy->-r ../requirements.txt (line 11)) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from spacy->-r ../requirements.txt (line 11)) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from spacy->-r ../requirements.txt (line 11)) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from spacy->-r ../requirements.txt (line 11)) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from spacy->-r ../requirements.txt (line 11)) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from spacy->-r ../requirements.txt (line 11)) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from spacy->-r ../requirements.txt (line 11)) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from spacy->-r ../requirements.txt (line 11)) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from spacy->-r ../requirements.txt (line 11)) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in d:\github\rag-based-profile-matching\venv\lib\site-packages (from spacy->-r ../requirements.txt (line 11)) (1.0.0)

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
# Download the spaCy English model (run once)
!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     -------------- ------------------------- 4.7/12.8 MB 52.3 MB/s eta 0:00:01
     --------------------------------- ----- 11.0/12.8 MB 35.5 MB/s eta 0:00:01
     ---------------------------------------- 12.8/12.8 MB 26.6 MB/s  0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

## Import Required Libraries

In this section we import all libraries required for the project.

The imports are grouped according to their purpose:

- File Handling
- PDF Processing
- Machine Learning
- Embedding Models
- Vector Database
- Metadata Extraction
- Visualization

In [3]:
import os
import json
import warnings
from pathlib import Path

import pandas as pd
from tqdm import tqdm
from dotenv import load_dotenv

warnings.filterwarnings("ignore")

# LangChain
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter

# OpenRouter
from langchain_openrouter import ChatOpenRouter

# ChromaDB
from langchain_chroma import Chroma

# Hybrid Search
from rank_bm25 import BM25Okapi

print("✅ Libraries imported successfully.")

✅ Libraries imported successfully.

# Configure the Environment

This project uses **OpenRouter** as the gateway for accessing Large Language Models (LLMs).

The API key is stored securely in a `.env` file located in the project root.

Example:

```text
OPENROUTER_API_KEY=your_openrouter_api_key
```

Using environment variables keeps sensitive credentials out of the source code and makes the project easier to deploy and share.

In [4]:
from dotenv import load_dotenv
import os

# Load environment variables
load_dotenv("../.env")

OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")

if not OPENROUTER_API_KEY:
    raise ValueError("❌ OPENROUTER_API_KEY not found in .env file.")

print("✅ OpenRouter API Key loaded successfully.")

✅ OpenRouter API Key loaded successfully.

# Initialize AI Models

A Retrieval-Augmented Generation (RAG) system consists of two primary AI components:

### 1. Embedding Model

The embedding model converts textual data into dense numerical vectors that capture semantic meaning. These embeddings enable efficient similarity search within the vector database.

Embedding Model:
- **text-embedding-3-small**

### 2. Large Language Model (LLM)

The Large Language Model (LLM) is responsible for understanding natural language and generating human-readable responses.

In this project, the LLM is used to:

- Extract resume metadata
- Explain candidate-job matches
- Generate structured JSON responses
- Support future enhancements such as resume summarization

LLM:
- **OpenAI GPT-4o Mini** (accessed through OpenRouter)

Separating retrieval (Embeddings) from reasoning (LLM) is a common architecture used in modern RAG systems.

In [5]:
# ============================================================
# Initialize Embedding Model
# ============================================================

embedding_model = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

print("✅ Embedding model initialized : sentence-transformers/all-MiniLM-L6-v2")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

✅ Embedding model initialized : sentence-transformers/all-MiniLM-L6-v2

In [6]:
# ============================================================
# Initialize LLM
# ============================================================

llm = ChatOpenRouter(
    model="openai/gpt-4o-mini",
    temperature=0.2,
    api_key=OPENROUTER_API_KEY,
    max_tokens=150
)

print("✅ LLM initialized : openai/gpt-4o-mini")

✅ LLM initialized : openai/gpt-4o-mini

# Load Resume Documents

The first stage of a Retrieval-Augmented Generation (RAG) pipeline is **document ingestion**.

In this step, we load all resume PDF files from the `data/resumes/` directory using LangChain's **PyPDFLoader**.

Each PDF is converted into one or more **Document** objects.

A `Document` contains:

- **page_content** – The extracted text from each page.
- **metadata** – Information such as the source file path and page number.

These documents will later be:
- Chunked into smaller sections
- Converted into embeddings
- Stored in the vector database for semantic retrieval

In [7]:
# ============================================================
# Configure Project Directories
# ============================================================

from pathlib import Path

# Project Root
PROJECT_ROOT = Path.cwd().parent

# Data Directories
DATA_DIR = PROJECT_ROOT / "data"

RESUME_DIR = DATA_DIR / "resumes"

JOB_DESCRIPTION_DIR = DATA_DIR / "job_descriptions"

OUTPUT_DIR = PROJECT_ROOT / "outputs"

VECTOR_STORE_DIR = PROJECT_ROOT / os.getenv(
    "VECTOR_STORE_DIR",
    "data/chroma_db"
)

# Create directories if they don't exist
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
VECTOR_STORE_DIR.mkdir(parents=True, exist_ok=True)

print(f"Project Root      : {PROJECT_ROOT}")
print(f"Resume Directory  : {RESUME_DIR}")
print(f"Vector Store      : {VECTOR_STORE_DIR}")

Project Root      : d:\GitHub\RAG-Based-Profile-matching
Resume Directory  : d:\GitHub\RAG-Based-Profile-matching\data\resumes
Vector Store      : d:\GitHub\RAG-Based-Profile-matching\data\chroma_db

In [8]:
# ============================================================
# Find Resume PDFs
# ============================================================

resume_files = sorted(RESUME_DIR.glob("*.pdf"))

print(f"Found {len(resume_files)} resume(s).\n")

for pdf in resume_files:
    print(pdf.name)

Found 34 resume(s).

alex_green.pdf
alice_smith.pdf
andrew_anderson.pdf
brandon_hernandez.pdf
brittany_white.pdf
chloe_harris.pdf
chloe_hill.pdf
chloe_jackson.pdf
chloe_wright.pdf
christopher_hall.pdf
daniel_clark.pdf
daniel_garcia.pdf
david_wilson.pdf
elena_lewis.pdf
emily_davis.pdf
ethan_young.pdf
hannah_scott.pdf
james_martinez.pdf
john_doe.pdf
justin_lee.pdf
kevin_allen.pdf
kevin_young.pdf
laura_hill.pdf
marcus_harris.pdf
marcus_lewis.pdf
michael_brown.pdf
priya_sharma.pdf
robert_chen.pdf
sarah_jenkins.pdf
sophia_taylor.pdf
victoria_martinez.pdf
victoria_walker.pdf
william_green.pdf
zoe_lewis.pdf

In [9]:
# ============================================================
# Load Resume Documents
# ============================================================

all_documents = []

for resume_path in tqdm(resume_files, desc="Loading Resumes"):

    loader = PyPDFLoader(str(resume_path))

    documents = loader.load()

    # Add custom metadata
    for doc in documents:
        doc.metadata["resume_name"] = resume_path.stem
        doc.metadata["resume_path"] = str(resume_path)

    all_documents.extend(documents)

print(f"\n✅ Total pages loaded: {len(all_documents)}")

Loading Resumes: 100%|██████████| 34/34 [00:01<00:00, 24.87it/s]

✅ Total pages loaded: 34

In [10]:
# Display one sample document

sample_doc = all_documents[0]

print("Metadata:")
print(sample_doc.metadata)

print("\nPreview:\n")
print(sample_doc.page_content[:1000])

Metadata:
{'producer': 'Microsoft® Word 2019', 'creator': 'Microsoft® Word 2019', 'creationdate': '2026-08-08T01:08:36+05:30', 'author': 'Mohankumar Markuli Chandrayigowda', 'moddate': '2026-08-08T01:08:36+05:30', 'source': 'd:\\GitHub\\RAG-Based-Profile-matching\\data\\resumes\\alex_green.pdf', 'total_pages': 1, 'page': 0, 'page_label': '1', 'resume_name': 'alex_green', 'resume_path': 'd:\\GitHub\\RAG-Based-Profile-matching\\data\\resumes\\alex_green.pdf'}

Preview:

ALEX GREEN
Email: alex.green14@example.com | Phone: +1-555-0114
Location: Austin, TX

PROFESSIONAL SUMMARY
Experienced Backend Engineer with 9 years of hands-on industry experience building
scalable systems and data products.

TECHNICAL SKILLS
Python, FastAPI, Django, PostgreSQL, Redis, Docker, AWS, GraphQL, Microservices, Linux,
Unit Testing, REST APIs

EDUCATION
Bachelor of Science in Computer Science, UC San Diego (2015)

PROFESSIONAL EXPERIENCE
Senior Backend Engineer | Tech Company E | 2020 – Present (4 years)
• Spearheaded key initiatives for backend engineer domain improving system efficiency by
18%.
• Utilized Python, FastAPI, Django, PostgreSQL to build scalable production workflows.
• Collaborated across multi-functional teams to deliver reliable enterprise solutions.

Backend Engineer | Software Solutions O | 2015 – 2020 (5 years)
• Developed core platform features using Python and FastAPI.
• Maintained automated test coverage and documentation.

In [30]:
for i, doc in enumerate(all_documents[:3]):
    print("=" * 80)
    print(f"Document {i+1}")
    print("Metadata:", doc.metadata)
    print(doc.page_content[:100])

================================================================================
Document 1
Metadata: {'producer': 'Microsoft® Word 2019', 'creator': 'Microsoft® Word 2019', 'creationdate': '2026-08-08T01:08:36+05:30', 'author': 'Mohankumar Markuli Chandrayigowda', 'moddate': '2026-08-08T01:08:36+05:30', 'source': 'd:\\GitHub\\RAG-Based-Profile-matching\\data\\resumes\\alex_green.pdf', 'total_pages': 1, 'page': 0, 'page_label': '1', 'resume_name': 'alex_green', 'resume_path': 'd:\\GitHub\\RAG-Based-Profile-matching\\data\\resumes\\alex_green.pdf'}
ALEX GREEN
Email: alex.green14@example.com | Phone: +1-555-0114
Location: Austin, TX

PROFESSION
================================================================================
Document 2
Metadata: {'producer': 'Microsoft® Word 2019', 'creator': 'Microsoft® Word 2019', 'creationdate': '2026-08-08T01:10:22+05:30', 'author': 'Mohankumar Markuli Chandrayigowda', 'moddate': '2026-08-08T01:10:22+05:30', 'source': 'd:\\GitHub\\RAG-Based-Profile-matching\\data\\resumes\\alice_smith.pdf', 'total_pages': 1, 'page': 0, 'page_label': '1', 'resume_name': 'alice_smith', 'resume_path': 'd:\\GitHub\\RAG-Based-Profile-matching\\data\\resumes\\alice_smith.pdf'}
ALICE SMITH
Email: alice.smith@devmail.com | Phone: +1-555-0102
Location: Seattle, WA

PROFESSIO
================================================================================
Document 3
Metadata: {'producer': 'Microsoft® Word 2019', 'creator': 'Microsoft® Word 2019', 'creationdate': '2026-08-08T01:14:34+05:30', 'author': 'Mohankumar Markuli Chandrayigowda', 'moddate': '2026-08-08T01:14:34+05:30', 'source': 'd:\\GitHub\\RAG-Based-Profile-matching\\data\\resumes\\andrew_anderson.pdf', 'total_pages': 1, 'page': 0, 'page_label': '1', 'resume_name': 'andrew_anderson', 'resume_path': 'd:\\GitHub\\RAG-Based-Profile-matching\\data\\resumes\\andrew_anderson.pdf'}
ANDREW ANDERSON
Email: andrew.anderson13@example.com | Phone: +1-555-0113
Location: San Francisco,

# Intelligent Document Chunking

Large Language Models and embedding models have context length limitations, making it inefficient to embed an entire resume as a single document.

Instead, each resume is divided into smaller, overlapping chunks.

### Why Chunking?

- Improves semantic search accuracy.
- Preserves local context within each chunk.
- Enables retrieval of the most relevant sections instead of the entire resume.
- Reduces embedding computation for future updates.

### Chunking Strategy

The chunk size and overlap are configured through the `.env` file.

Configuration:

- **Chunk Size:** 1000 characters
- **Chunk Overlap:** 200 characters

The overlap helps preserve context between adjacent chunks, ensuring important information is not split abruptly.

In [41]:
# ============================================================
# Configure Text Splitter
# ============================================================

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=int(os.getenv("CHUNK_SIZE")),
    chunk_overlap=int(os.getenv("CHUNK_OVERLAP")),
    separators=[
        "\n\n",
        "\n",
        ". ",
        " ",
        ""
    ]
)

print("✅ Text splitter initialized.")

✅ Text splitter initialized.

In [42]:
# ============================================================
# Split Documents into Chunks
# ============================================================

chunked_documents = text_splitter.split_documents(all_documents)

print(f"Total Chunks Created: {len(chunked_documents)}")

Total Chunks Created: 47

In [43]:
# ============================================================
# Inspect a Sample Chunk
# ============================================================

sample_chunk = chunked_documents[0]

print("Metadata:")
print(sample_chunk.metadata)

print("\nChunk Length:")
print(len(sample_chunk.page_content))

print("\nChunk Preview:\n")
print(sample_chunk.page_content[:1000])

Metadata:
{'producer': 'Microsoft® Word 2019', 'creator': 'Microsoft® Word 2019', 'creationdate': '2026-08-08T01:08:36+05:30', 'author': 'Mohankumar Markuli Chandrayigowda', 'moddate': '2026-08-08T01:08:36+05:30', 'source': 'd:\\GitHub\\RAG-Based-Profile-matching\\data\\resumes\\alex_green.pdf', 'total_pages': 1, 'page': 0, 'page_label': '1', 'resume_name': 'alex_green', 'resume_path': 'd:\\GitHub\\RAG-Based-Profile-matching\\data\\resumes\\alex_green.pdf'}

Chunk Length:
994

Chunk Preview:

ALEX GREEN
Email: alex.green14@example.com | Phone: +1-555-0114
Location: Austin, TX

PROFESSIONAL SUMMARY
Experienced Backend Engineer with 9 years of hands-on industry experience building
scalable systems and data products.

TECHNICAL SKILLS
Python, FastAPI, Django, PostgreSQL, Redis, Docker, AWS, GraphQL, Microservices, Linux,
Unit Testing, REST APIs

EDUCATION
Bachelor of Science in Computer Science, UC San Diego (2015)

PROFESSIONAL EXPERIENCE
Senior Backend Engineer | Tech Company E | 2020 – Present (4 years)
• Spearheaded key initiatives for backend engineer domain improving system efficiency by
18%.
• Utilized Python, FastAPI, Django, PostgreSQL to build scalable production workflows.
• Collaborated across multi-functional teams to deliver reliable enterprise solutions.

Backend Engineer | Software Solutions O | 2015 – 2020 (5 years)
• Developed core platform features using Python and FastAPI.
• Maintained automated test coverage and documentation.

# Generate Embeddings and Create the Vector Database

Once the resume documents have been split into meaningful chunks, the next step is to convert each chunk into a numerical vector representation called an **embedding**.

Embeddings capture the semantic meaning of text, enabling similarity-based retrieval instead of exact keyword matching.

In this project, the embedding model converts every resume chunk into a dense vector, which is then stored in **ChromaDB**, a persistent vector database.

### Why ChromaDB?

- Persistent storage on disk
- Fast similarity search
- Metadata filtering
- Seamless integration with LangChain
- Lightweight and suitable for local RAG applications

At the end of this step, every resume chunk will be indexed and ready for semantic retrieval.

In [44]:
# ============================================================
# Create Chroma Vector Store
# ============================================================

vector_store = Chroma.from_documents(
    documents=chunked_documents,
    embedding=embedding_model,
    persist_directory=str(VECTOR_STORE_DIR)
)

print("✅ Vector Store Created Successfully")

✅ Vector Store Created Successfully

In [45]:
print(vector_store)

<langchain_chroma.vectorstores.Chroma object at 0x000002A0605CC590>

In [46]:
collection = vector_store._collection

print(f"Total Chunks Stored : {collection.count()}")

Total Chunks Stored : 47

In [70]:
TOP_K = 10

retriever = vector_store.as_retriever(
    search_kwargs={"k": TOP_K}
)

print("✅ Retriever created successfully.")

✅ Retriever created successfully.

#  Load Job Description

The Resume RAG system supports two ways of providing a job description:

1. **Select an existing Job Description** from the `data/job_descriptions/` directory.
2. **Provide a custom Job Description** by entering the path to a text file.

This flexibility allows recruiters to evaluate resumes against predefined roles or new hiring requirements without modifying the code.

In [49]:
# ============================================================
# Available Job Descriptions
# ============================================================

jd_files = sorted(JOB_DESCRIPTION_DIR.glob("*.txt"))

print("Available Job Descriptions:\n")

for index, jd in enumerate(jd_files, start=1):
    print(f"{index}. {jd.stem}")

Available Job Descriptions:

1. jd_ai_product_manager
2. jd_devops_cloud_architect
3. jd_frontend_react_engineer
4. jd_fullstack_python_dev
5. jd_senior_data_engineer
6. jd_senior_ml_engineer

In [57]:
# ============================================================
# Select Job Description
# ============================================================

print("\nChoose an option:")

print("1. Select an existing Job Description")

print("2. Use your own Job Description (.txt file)")

choice = input("\nEnter your choice (1 or 2): ").strip()

Choose an option:
1. Select an existing Job Description
2. Use your own Job Description (.txt file)

In [58]:
# ============================================================
# Load Selected Job Description
# ============================================================

if choice == "1":

    jd_number = int(input("Enter the Job Description number: "))

    selected_jd = jd_files[jd_number - 1]

elif choice == "2":

    custom_path = input("Enter the full path of your Job Description (.txt): ").strip().strip('"')

    selected_jd = Path(custom_path)

    if not selected_jd.exists():
        raise FileNotFoundError(f"File not found: {selected_jd}")

else:
    raise ValueError("Invalid choice.")

print(f"\nSelected Job Description: {selected_jd.name}")

Selected Job Description: jd_devops_cloud_architect.txt

In [59]:
# ============================================================
# Read Job Description
# ============================================================

with open(selected_jd, "r", encoding="utf-8") as file:
    job_description = file.read()

print(job_description)

JOB TITLE: Senior DevOps & Cloud Architect
LOCATION: Austin, TX / Remote
EXPERIENCE REQUIRED: 6+ years

JOB DESCRIPTION:
Join our cloud operations team to build scalable, automated Infrastructure-as-Code. You will manage multi-region Kubernetes clusters on AWS, automate CI/CD pipelines, and monitor telemetry with Prometheus/Grafana.

MUST-HAVE REQUIREMENTS:
- 6+ years of DevOps / Infrastructure experience.
- Mastery of Terraform, Ansible, and Infrastructure as Code (IaC).
- Heavy hands-on experience with Kubernetes (EKS/GKE) and Docker.
- Advanced scripting in Python or Bash.
- Deep AWS expertise (VPC, IAM, EKS, EC2).

NICE-TO-HAVE SKILLS:
- GitOps experience with ArgoCD or Flux.
- Certified AWS Solutions Architect or CKA certification.

# Step 8: Semantic Resume Retrieval

The objective of semantic retrieval is to identify the resume chunks that are most relevant to the given job description.

Unlike traditional keyword-based search, semantic retrieval compares the **meaning** of the job description with the meaning of each resume chunk using vector embeddings.

In this step:

- The job description is converted into an embedding.
- ChromaDB performs similarity search over all indexed resume chunks.
- The Top-K most relevant chunks are retrieved along with their similarity scores.

These retrieved chunks will serve as the input for metadata extraction, hybrid search, and candidate ranking.

In [66]:
# ============================================================
# Semantic Search
# ============================================================

TOP_K = 10

semantic_results = vector_store.similarity_search_with_score(
    query=job_description,
    k=TOP_K
)

print(f"Retrieved {len(semantic_results)} matching resume chunks.")

Retrieved 10 matching resume chunks.

In [67]:
# ============================================================
# Inspect Retrieved Results
# ============================================================

document, score = semantic_results[0]

print("Similarity Score :", score)

print("\nMetadata")

print(document.metadata)

print("\nPreview\n")

print(document.page_content[:800])

Similarity Score : 0.3658221662044525

Metadata
{'page_label': '1', 'producer': 'Microsoft® Word 2019', 'resume_path': 'd:\\GitHub\\RAG-Based-Profile-matching\\data\\resumes\\emily_davis.pdf', 'moddate': '2026-08-08T01:34:27+05:30', 'source': 'd:\\GitHub\\RAG-Based-Profile-matching\\data\\resumes\\emily_davis.pdf', 'total_pages': 1, 'page': 0, 'resume_name': 'emily_davis', 'creationdate': '2026-08-08T01:34:27+05:30', 'author': 'Mohankumar Markuli Chandrayigowda', 'creator': 'Microsoft® Word 2019'}

Preview

EMILY DAVIS
Email: emily.davis@cloudworks.io | Phone: +1-555-0104
Location: Austin, TX

PROFESSIONAL SUMMARY
Senior DevOps & Cloud Architect with 8 years of experience building resilient AWS &
Kubernetes infrastructure.

TECHNICAL SKILLS
Terraform, Kubernetes, Docker, AWS, Python, Bash, Ansible, Prometheus, Grafana, Jenkins,
GitLab CI, ArgoCD

EDUCATION
Bachelor of Science in Computer Information Systems, UT Austin (2016)

PROFESSIONAL EXPERIENCE
Senior DevOps Architect | SkyHigh Infrastructure | 2020 – Present (4 years)
• Managed multi-region AWS EKS clusters hosting 300+ microservices.
• Reduced cloud infrastructure cost by 35% through spot instances and automated auto-
scaling.

Infrastructure Engineer | DataPipe Cloud | 2016 – 2020 (4 years)
• Automated zero-downti

In [68]:
# ============================================================
# Display Top-K Results
# ============================================================

for rank, (document, score) in enumerate(semantic_results, start=1):

    print("=" * 100)

    print(f"Rank              : {rank}")
    print(f"Resume            : {document.metadata['resume_name']}")
    print(f"Page              : {document.metadata['page']}")
    print(f"Similarity Score  : {score:.4f}")

    print("\nPreview\n")

    print(document.page_content[:400])

====================================================================================================
Rank              : 1
Resume            : emily_davis
Page              : 0
Similarity Score  : 0.3658

Preview

EMILY DAVIS
Email: emily.davis@cloudworks.io | Phone: +1-555-0104
Location: Austin, TX

PROFESSIONAL SUMMARY
Senior DevOps & Cloud Architect with 8 years of experience building resilient AWS &
Kubernetes infrastructure.

TECHNICAL SKILLS
Terraform, Kubernetes, Docker, AWS, Python, Bash, Ansible, Prometheus, Grafana, Jenkins,
GitLab CI, ArgoCD

EDUCATION
Bachelor of Science in Computer
====================================================================================================
Rank              : 2
Resume            : marcus_lewis
Page              : 0
Similarity Score  : 0.4939

Preview

MARCUS LEWIS
Email: marcus.lewis18@example.com | Phone: +1-555-0118
Location: San Francisco, CA

PROFESSIONAL SUMMARY
Experienced DevOps Engineer with 10 years of hands-on industry experience building
scalable systems and data products.

TECHNICAL SKILLS
Docker, Kubernetes, Terraform, AWS, CI/CD, Python, Bash, Prometheus, ArgoCD, REST APIs,
Unit Testing, Linux

EDUCATION
Bachelor of S
====================================================================================================
Rank              : 3
Resume            : kevin_allen
Page              : 0
Similarity Score  : 0.7085

Preview

KEVIN ALLEN
Email: kevin.allen27@example.com | Phone: +1-555-0127
Location: Chicago, IL

PROFESSIONAL SUMMARY
Experienced Data Engineer with 7 years of hands-on industry experience building scalable
systems and data products.

TECHNICAL SKILLS
Python, SQL, Apache Spark, Airflow, Snowflake, Kafka, dbt, AWS Redshift, Docker, Linux, Unit
Testing, REST APIs

EDUCATION
Bachelor of Science
====================================================================================================
Rank              : 4
Resume            : justin_lee
Page              : 0
Similarity Score  : 0.7408

Preview

JUSTIN LEE
Email: justin.lee26@example.com | Phone: +1-555-0126
Location: Remote

PROFESSIONAL SUMMARY
Experienced Backend Engineer with 10 years of hands-on industry experience building
scalable systems and data products.

TECHNICAL SKILLS
Python, FastAPI, Django, PostgreSQL, Redis, Docker, AWS, GraphQL, Microservices, CI/CD,
REST APIs, Jira

EDUCATION
Bachelor of Science in Computer
====================================================================================================
Rank              : 5
Resume            : alex_green
Page              : 0
Similarity Score  : 0.7580

Preview

ALEX GREEN
Email: alex.green14@example.com | Phone: +1-555-0114
Location: Austin, TX

PROFESSIONAL SUMMARY
Experienced Backend Engineer with 9 years of hands-on industry experience building
scalable systems and data products.

TECHNICAL SKILLS
Python, FastAPI, Django, PostgreSQL, Redis, Docker, AWS, GraphQL, Microservices, Linux,
Unit Testing, REST APIs

EDUCATION
Bachelor of Science
====================================================================================================
Rank              : 6
Resume            : laura_hill
Page              : 0
Similarity Score  : 0.7689

Preview

LAURA HILL
Email: laura.hill17@example.com | Phone: +1-555-0117
Location: Boston, MA

PROFESSIONAL SUMMARY
Experienced Data Engineer with 3 years of hands-on industry experience building scalable
systems and data products.

TECHNICAL SKILLS
Python, SQL, Apache Spark, Airflow, Snowflake, Kafka, dbt, AWS Redshift, Docker, REST APIs,
Git, Linux

EDUCATION
Bachelor of Science in Computer
====================================================================================================
Rank              : 7
Resume            : christopher_hall
Page              : 0
Similarity Score  : 0.7739

Preview

CHRISTOPHER HALL
Email: christopher.hall30@example.com | Phone: +1-555-0130
Location: Boston, MA

PROFESSIONAL SUMMARY
Experienced Backend Engineer with 7 years of hands-on industry experience building
scalable systems and data products.

TECHNICAL SKILLS
Python, FastAPI, Django, PostgreSQL, Redis, Docker, AWS, GraphQL, Microservices, Jira,
Agile, Linux

EDUCATION
Bachelor of Science
====================================================================================================
Rank              : 8
Resume            : elena_lewis
Page              : 0
Similarity Score  : 0.7856

Preview

ELENA LEWIS
Email: elena.lewis15@example.com | Phone: +1-555-0115
Location: Chicago, IL

PROFESSIONAL SUMMARY
Experienced Data Engineer with 8 years of hands-on industry experience building scalable
systems and data products.

TECHNICAL SKILLS
Python, SQL, Apache Spark, Airflow, Snowflake, Kafka, dbt, AWS Redshift, Docker, REST APIs,
Git, Agile

EDUCATION
Bachelor of Science in Comput
====================================================================================================
Rank              : 9
Resume            : daniel_clark
Page              : 0
Similarity Score  : 0.7923

Preview

DANIEL CLARK
Email: daniel.clark34@example.com | Phone: +1-555-0134
Location: Austin, TX

PROFESSIONAL SUMMARY
Experienced Data Engineer with 11 years of hands-on industry experience building scalable
systems and data products.

TECHNICAL SKILLS
Python, SQL, Apache Spark, Airflow, Snowflake, Kafka, dbt, AWS Redshift, Docker, CI/CD,
Agile, Linux

EDUCATION
Bachelor of Science in Comput
====================================================================================================
Rank              : 10
Resume            : ethan_young
Page              : 0
Similarity Score  : 0.7973

Preview

ETHAN YOUNG
Email: ethan.young12@example.com | Phone: +1-555-0112
Location: Seattle, WA

PROFESSIONAL SUMMARY
Experienced Data Engineer with 9 years of hands-on industry experience building scalable
systems and data products.

TECHNICAL SKILLS
Python, SQL, Apache Spark, Airflow, Snowflake, Kafka, dbt, AWS Redshift, Docker, Git, Linux,
CI/CD

EDUCATION
Bachelor of Science in Computer S

In [71]:
retriever.invoke(job_description)

[Document(id='696351ac-8735-4423-9f1a-9a1d90cb237a', metadata={'producer': 'Microsoft® Word 2019', 'creationdate': '2026-08-08T01:34:27+05:30', 'page_label': '1', 'page': 0, 'author': 'Mohankumar Markuli Chandrayigowda', 'resume_name': 'emily_davis', 'creator': 'Microsoft® Word 2019', 'total_pages': 1, 'source': 'd:\\GitHub\\RAG-Based-Profile-matching\\data\\resumes\\emily_davis.pdf', 'resume_path': 'd:\\GitHub\\RAG-Based-Profile-matching\\data\\resumes\\emily_davis.pdf', 'moddate': '2026-08-08T01:34:27+05:30'}, page_content='EMILY DAVIS \nEmail: emily.davis@cloudworks.io | Phone: +1-555-0104 \nLocation: Austin, TX \n \nPROFESSIONAL SUMMARY \nSenior DevOps & Cloud Architect with 8 years of experience building resilient AWS & \nKubernetes infrastructure. \n \nTECHNICAL SKILLS \nTerraform, Kubernetes, Docker, AWS, Python, Bash, Ansible, Prometheus, Grafana, Jenkins, \nGitLab CI, ArgoCD \n \nEDUCATION \nBachelor of Science in Computer Information Systems, UT Austin (2016) \n \nPROFESSIONAL EXPERIENCE \nSenior DevOps Architect | SkyHigh Infrastructure | 2020 – Present (4 years) \n• Managed multi-region AWS EKS clusters hosting 300+ microservices. \n• Reduced cloud infrastructure cost by 35% through spot instances and automated auto-\nscaling. \n \nInfrastructure Engineer | DataPipe Cloud | 2016 – 2020 (4 years) \n• Automated zero-downtime deployment pipelines with Terraform and GitOps (ArgoCD).'),
 Document(id='ccce5960-5ef9-4ec8-ab51-11029d0c71ab', metadata={'producer': 'Microsoft® Word 2019', 'creator': 'Microsoft® Word 2019', 'page': 0, 'author': 'Mohankumar Markuli Chandrayigowda', 'moddate': '2026-08-08T01:50:00+05:30', 'source': 'd:\\GitHub\\RAG-Based-Profile-matching\\data\\resumes\\marcus_lewis.pdf', 'creationdate': '2026-08-08T01:50:00+05:30', 'resume_path': 'd:\\GitHub\\RAG-Based-Profile-matching\\data\\resumes\\marcus_lewis.pdf', 'resume_name': 'marcus_lewis', 'page_label': '1', 'total_pages': 1}, page_content='MARCUS LEWIS \nEmail: marcus.lewis18@example.com | Phone: +1-555-0118 \nLocation: San Francisco, CA \n \nPROFESSIONAL SUMMARY \nExperienced DevOps Engineer with 10 years of hands-on industry experience building \nscalable systems and data products. \n \nTECHNICAL SKILLS \nDocker, Kubernetes, Terraform, AWS, CI/CD, Python, Bash, Prometheus, ArgoCD, REST APIs, \nUnit Testing, Linux \n \nEDUCATION \nBachelor of Science in Computer Science, UC San Diego (2014) \n \nPROFESSIONAL EXPERIENCE \nSenior DevOps Engineer | Tech Company I | 2020 – Present (4 years) \n• Spearheaded key initiatives for devops engineer domain improving system efficiency by \n36%. \n• Utilized Docker, Kubernetes, Terraform, AWS to build scalable production workflows. \n• Collaborated across multi-functional teams to deliver reliable enterprise solutions. \n \nDevOps Engineer | Software Solutions S | 2014 – 2020 (6 years) \n• Developed core platform features using Docker and Kubernetes. \n• Maintained automated test coverage and documentation.'),
 Document(id='81e4b24f-479c-4b31-805a-85a4ab4a07b5', metadata={'page': 0, 'creator': 'Microsoft® Word 2019', 'author': 'Mohankumar Markuli Chandrayigowda', 'source': 'd:\\GitHub\\RAG-Based-Profile-matching\\data\\resumes\\kevin_allen.pdf', 'creationdate': '2026-08-08T01:46:48+05:30', 'total_pages': 1, 'moddate': '2026-08-08T01:46:48+05:30', 'producer': 'Microsoft® Word 2019', 'resume_path': 'd:\\GitHub\\RAG-Based-Profile-matching\\data\\resumes\\kevin_allen.pdf', 'resume_name': 'kevin_allen', 'page_label': '1'}, page_content='KEVIN ALLEN \nEmail: kevin.allen27@example.com | Phone: +1-555-0127 \nLocation: Chicago, IL \n \nPROFESSIONAL SUMMARY \nExperienced Data Engineer with 7 years of hands-on industry experience building scalable \nsystems and data products. \n \nTECHNICAL SKILLS \nPython, SQL, Apache Spark, Airflow, Snowflake, Kafka, dbt, AWS Redshift, Docker, Linux, Unit \nTesting, REST APIs \n \nEDUCATION \nBachelor of Science in Computer Science, University of Southern California (2017) \n \nPROFESSIONAL EXPERIENCE \nSenior Data Engineer | Tech Company H | 2020 – Present (4 years) \n• Spearheaded key initiatives for data engineer domain improving system efficiency by 39%. \n• Utilized Python, SQL, Apache Spark, Airflow to build scalable production workflows. \n• Collaborated across multi-functional teams to deliver reliable enterprise solutions. \n \nData Engineer | Software Solutions R | 2017 – 2020 (3 years) \n• Developed core platform features using Python and SQL. \n• Maintained automated test coverage and documentation.'),
 Document(id='64955fd5-622c-4611-b5d8-4abbf2950468', metadata={'creationdate': '2026-08-08T01:45:57+05:30', 'page_label': '1', 'resume_path': 'd:\\GitHub\\RAG-Based-Profile-matching\\data\\resumes\\justin_lee.pdf', 'page': 0, 'moddate': '2026-08-08T01:45:57+05:30', 'producer': 'Microsoft® Word 2019', 'source': 'd:\\GitHub\\RAG-Based-Profile-matching\\data\\resumes\\justin_lee.pdf', 'resume_name': 'justin_lee', 'creator': 'Microsoft® Word 2019', 'total_pages': 1, 'author': 'Mohankumar Markuli Chandrayigowda'}, page_content='JUSTIN LEE \nEmail: justin.lee26@example.com | Phone: +1-555-0126 \nLocation: Remote \n \nPROFESSIONAL SUMMARY \nExperienced Backend Engineer with 10 years of hands-on industry experience building \nscalable systems and data products. \n \nTECHNICAL SKILLS \nPython, FastAPI, Django, PostgreSQL, Redis, Docker, AWS, GraphQL, Microservices, CI/CD, \nREST APIs, Jira \n \nEDUCATION \nBachelor of Science in Computer Science, Carnegie Mellon University (2014) \n \nPROFESSIONAL EXPERIENCE \nSenior Backend Engineer | Tech Company G | 2020 – Present (4 years) \n• Spearheaded key initiatives for backend engineer domain improving system efficiency by \n39%. \n• Utilized Python, FastAPI, Django, PostgreSQL to build scalable production workflows. \n• Collaborated across multi-functional teams to deliver reliable enterprise solutions. \n \nBackend Engineer | Software Solutions Q | 2014 – 2020 (6 years) \n• Developed core platform features using Python and FastAPI. \n• Maintained automated test coverage and documentation.'),
 Document(id='c96ccf44-aa12-49fe-8db0-4be6f1d1e058', metadata={'page': 0, 'resume_path': 'd:\\GitHub\\RAG-Based-Profile-matching\\data\\resumes\\alex_green.pdf', 'total_pages': 1, 'producer': 'Microsoft® Word 2019', 'resume_name': 'alex_green', 'page_label': '1', 'creationdate': '2026-08-08T01:08:36+05:30', 'creator': 'Microsoft® Word 2019', 'moddate': '2026-08-08T01:08:36+05:30', 'source': 'd:\\GitHub\\RAG-Based-Profile-matching\\data\\resumes\\alex_green.pdf', 'author': 'Mohankumar Markuli Chandrayigowda'}, page_content='ALEX GREEN \nEmail: alex.green14@example.com | Phone: +1-555-0114 \nLocation: Austin, TX \n \nPROFESSIONAL SUMMARY \nExperienced Backend Engineer with 9 years of hands-on industry experience building \nscalable systems and data products. \n \nTECHNICAL SKILLS \nPython, FastAPI, Django, PostgreSQL, Redis, Docker, AWS, GraphQL, Microservices, Linux, \nUnit Testing, REST APIs \n \nEDUCATION \nBachelor of Science in Computer Science, UC San Diego (2015) \n \nPROFESSIONAL EXPERIENCE \nSenior Backend Engineer | Tech Company E | 2020 – Present (4 years) \n• Spearheaded key initiatives for backend engineer domain improving system efficiency by \n18%. \n• Utilized Python, FastAPI, Django, PostgreSQL to build scalable production workflows. \n• Collaborated across multi-functional teams to deliver reliable enterprise solutions. \n \nBackend Engineer | Software Solutions O | 2015 – 2020 (5 years) \n• Developed core platform features using Python and FastAPI. \n• Maintained automated test coverage and documentation.'),
 Document(id='6ee312df-8b1e-44d8-b047-9e5f06e491de', metadata={'creator': 'Microsoft® Word 2019', 'page_label': '1', 'page': 0, 'resume_name': 'laura_hill', 'source': 'd:\\GitHub\\RAG-Based-Profile-matching\\data\\resumes\\laura_hill.pdf', 'producer': 'Microsoft® Word 2019', 'creationdate': '2026-08-08T01:48:16+05:30', 'total_pages': 1, 'author': 'Mohankumar Markuli Chandrayigowda', 'resume_path': 'd:\\GitHub\\RAG-Based-Profile-matching\\data\\resumes\\laura_hill.pdf', 'moddate': '2026-08-08T01:48:16+05:30'}, page_content='LAURA HILL \nEmail: laura.hill17@example.com | Phone: +1-555-0117 \nLocation: Boston, MA \n \nPROFESSIONAL SUMMARY \nExperienced Data Engineer with 3 years of hands-on industry experience building scalable \nsystems and data products. \n \nTECHNICAL SKILLS \nPython, SQL, Apache Spark, Airflow, Snowflake, Kafka, dbt, AWS Redshift, Docker, REST APIs, \nGit, Linux \n \nEDUCATION \nBachelor of Science in Computer Science, University of Texas at Austin (2021) \n \nPROFESSIONAL EXPERIENCE \nSenior Data Engineer | Tech Company H | 2020 – Present (4 years) \n• Spearheaded key initiatives for data engineer domain improving system efficiency by 42%. \n• Utilized Python, SQL, Apache Spark, Airflow to build scalable production workflows. \n• Collaborated across multi-functional teams to deliver reliable enterprise solutions. \n \nData Engineer | Software Solutions R | 2021 – 2020 (-1 years) \n• Developed core platform features using Python and SQL. \n• Maintained automated test coverage and documentation.'),
 Document(id='27f151fc-9422-453f-a6a3-2cd9a3f27665', metadata={'creationdate': '2026-08-08T01:28:26+05:30', 'author': 'Mohankumar Markuli Chandrayigowda', 'creator': 'Microsoft® Word 2019', 'page': 0, 'source': 'd:\\GitHub\\RAG-Based-Profile-matching\\data\\resumes\\christopher_hall.pdf', 'page_label': '1', 'total_pages': 1, 'resume_name': 'christopher_hall', 'producer': 'Microsoft® Word 2019', 'resume_path': 'd:\\GitHub\\RAG-Based-Profile-matching\\data\\resumes\\christopher_hall.pdf', 'moddate': '2026-08-08T01:28:26+05:30'}, page_content='CHRISTOPHER HALL \nEmail: christopher.hall30@example.com | Phone: +1-555-0130 \nLocation: Boston, MA \n \nPROFESSIONAL SUMMARY \nExperienced Backend Engineer with 7 years of hands-on industry experience building \nscalable systems and data products. \n \nTECHNICAL SKILLS \nPython, FastAPI, Django, PostgreSQL, Redis, Docker, AWS, GraphQL, Microservices, Jira, \nAgile, Linux \n \nEDUCATION \nBachelor of Science in Computer Science, University of Southern California (2017) \n \nPROFESSIONAL EXPERIENCE \nSenior Backend Engineer | Tech Company A | 2020 – Present (4 years) \n• Spearheaded key initiatives for backend engineer domain improving system efficiency by \n44%. \n• Utilized Python, FastAPI, Django, PostgreSQL to build scalable production workflows. \n• Collaborated across multi-functional teams to deliver reliable enterprise solutions. \n \nBackend Engineer | Software Solutions K | 2017 – 2020 (3 years) \n• Developed core platform features using Python and FastAPI.'),
 Document(id='d495b551-a508-43ee-947b-9adedcb3f56a', metadata={'resume_path': 'd:\\GitHub\\RAG-Based-Profile-matching\\data\\resumes\\elena_lewis.pdf', 'author': 'Mohankumar Markuli Chandrayigowda', 'producer': 'Microsoft® Word 2019', 'resume_name': 'elena_lewis', 'total_pages': 1, 'moddate': '2026-08-08T01:33:31+05:30', 'page_label': '1', 'creationdate': '2026-08-08T01:33:31+05:30', 'source': 'd:\\GitHub\\RAG-Based-Profile-matching\\data\\resumes\\elena_lewis.pdf', 'page': 0, 'creator': 'Microsoft® Word 2019'}, page_content='ELENA LEWIS \nEmail: elena.lewis15@example.com | Phone: +1-555-0115 \nLocation: Chicago, IL \n \nPROFESSIONAL SUMMARY \nExperienced Data Engineer with 8 years of hands-on industry experience building scalable \nsystems and data products. \n \nTECHNICAL SKILLS \nPython, SQL, Apache Spark, Airflow, Snowflake, Kafka, dbt, AWS Redshift, Docker, REST APIs, \nGit, Agile \n \nEDUCATION \nBachelor of Science in Computer Science, UC San Diego (2016) \n \nPROFESSIONAL EXPERIENCE \nSenior Data Engineer | Tech Company F | 2020 – Present (4 years) \n• Spearheaded key initiatives for data engineer domain improving system efficiency by 32%. \n• Utilized Python, SQL, Apache Spark, Airflow to build scalable production workflows. \n• Collaborated across multi-functional teams to deliver reliable enterprise solutions. \n \nData Engineer | Software Solutions P | 2016 – 2020 (4 years) \n• Developed core platform features using Python and SQL. \n• Maintained automated test coverage and documentation.'),
 Document(id='03e8bd76-ac04-492b-802b-91f4d2d7ef50', metadata={'creator': 'Microsoft® Word 2019', 'creationdate': '2026-08-08T01:29:42+05:30', 'producer': 'Microsoft® Word 2019', 'page_label': '1', 'author': 'Mohankumar Markuli Chandrayigowda', 'moddate': '2026-08-08T01:29:42+05:30', 'source': 'd:\\GitHub\\RAG-Based-Profile-matching\\data\\resumes\\daniel_clark.pdf', 'page': 0, 'total_pages': 1, 'resume_path': 'd:\\GitHub\\RAG-Based-Profile-matching\\data\\resumes\\daniel_clark.pdf', 'resume_name': 'daniel_clark'}, page_content='DANIEL CLARK \nEmail: daniel.clark34@example.com | Phone: +1-555-0134 \nLocation: Austin, TX \n \nPROFESSIONAL SUMMARY \nExperienced Data Engineer with 11 years of hands-on industry experience building scalable \nsystems and data products. \n \nTECHNICAL SKILLS \nPython, SQL, Apache Spark, Airflow, Snowflake, Kafka, dbt, AWS Redshift, Docker, CI/CD, \nAgile, Linux \n \nEDUCATION \nBachelor of Science in Computer Science, University of Texas at Austin (2013) \n \nPROFESSIONAL EXPERIENCE \nSenior Data Engineer | Tech Company E | 2020 – Present (4 years) \n• Spearheaded key initiatives for data engineer domain improving system efficiency by 32%. \n• Utilized Python, SQL, Apache Spark, Airflow to build scalable production workflows. \n• Collaborated across multi-functional teams to deliver reliable enterprise solutions. \n \nData Engineer | Software Solutions O | 2013 – 2020 (7 years) \n• Developed core platform features using Python and SQL. \n• Maintained automated test coverage and documentation.'),
 Document(id='cdb9fbde-2145-4866-8e74-3b94fd4d7950', metadata={'creator': 'Microsoft® Word 2019', 'total_pages': 1, 'resume_path': 'd:\\GitHub\\RAG-Based-Profile-matching\\data\\resumes\\ethan_young.pdf', 'producer': 'Microsoft® Word 2019', 'source': 'd:\\GitHub\\RAG-Based-Profile-matching\\data\\resumes\\ethan_young.pdf', 'page_label': '1', 'creationdate': '2026-08-08T01:35:30+05:30', 'moddate': '2026-08-08T01:35:30+05:30', 'author': 'Mohankumar Markuli Chandrayigowda', 'page': 0, 'resume_name': 'ethan_young'}, page_content='ETHAN YOUNG \nEmail: ethan.young12@example.com | Phone: +1-555-0112 \nLocation: Seattle, WA \n \nPROFESSIONAL SUMMARY \nExperienced Data Engineer with 9 years of hands-on industry experience building scalable \nsystems and data products. \n \nTECHNICAL SKILLS \nPython, SQL, Apache Spark, Airflow, Snowflake, Kafka, dbt, AWS Redshift, Docker, Git, Linux, \nCI/CD \n \nEDUCATION \nBachelor of Science in Computer Science, Carnegie Mellon University (2015) \n \nPROFESSIONAL EXPERIENCE \nSenior Data Engineer | Tech Company C | 2020 – Present (4 years) \n• Spearheaded key initiatives for data engineer domain improving system efficiency by 31%. \n• Utilized Python, SQL, Apache Spark, Airflow to build scalable production workflows. \n• Collaborated across multi-functional teams to deliver reliable enterprise solutions. \n \nData Engineer | Software Solutions M | 2015 – 2020 (5 years) \n• Developed core platform features using Python and SQL. \n• Maintained automated test coverage and documentation.')]

# Extract Candidate Metadata

To improve candidate ranking and filtering, we extract structured information from the retrieved resume chunks.

The extracted metadata includes:

- Candidate Name
- Technical Skills
- Years of Experience
- Highest Education

This metadata will be used in later stages for:

- Hybrid Search
- Must-have Skill Filtering
- Candidate Ranking
- Match Scoring
- JSON Output

Instead of relying on regular expressions, we use the Large Language Model to extract structured information in JSON format, making the solution more robust across different resume formats.

In [76]:
from langchain_core.prompts import ChatPromptTemplate

metadata_prompt = ChatPromptTemplate.from_messages([
    (
        "system",
        """You are an expert resume parser.

Extract:
- candidate_name
- skills
- experience_years
- education

Return ONLY valid JSON.
"""
    ),
    (
        "human",
        "{resume}"
    )
])

In [77]:
import json

candidate_metadata = []

for document, score in semantic_results:

    try:

        prompt = metadata_prompt.format_messages(
            resume=document.page_content
        )

        response = llm.invoke(prompt)

        metadata = json.loads(response.content)

        metadata["resume_name"] = document.metadata.get("resume_name")
        metadata["resume_path"] = document.metadata.get("resume_path")
        metadata["semantic_score"] = score

        candidate_metadata.append(metadata)

    except Exception as e:

        print(f"Error processing {document.metadata.get('resume_name')}: {e}")

In [78]:
response_text = response.content.strip()

if response_text.startswith("```"):
    response_text = response_text.replace("```json", "").replace("```", "").strip()

metadata = json.loads(response_text)

# Hybrid Search

Semantic search is excellent at understanding context, but it may not always prioritize exact technical requirements such as programming languages, frameworks, certifications, or tools.

To improve retrieval quality, we combine:

1. **Semantic Search** – Finds resumes with similar meaning using vector embeddings.
2. **Keyword Search (BM25)** – Rewards resumes containing important terms from the job description.

This hybrid approach produces more accurate candidate rankings by leveraging the strengths of both retrieval techniques.

In [79]:
# ============================================================
# Build BM25 Index
# ============================================================

corpus = [doc.page_content for doc in chunked_documents]

tokenized_corpus = [doc.lower().split() for doc in corpus]

bm25 = BM25Okapi(tokenized_corpus)

print("✅ BM25 index created.")

✅ BM25 index created.

In [80]:
# ============================================================
# BM25 Search
# ============================================================

query_tokens = job_description.lower().split()

bm25_scores = bm25.get_scores(query_tokens)

print(f"Calculated BM25 scores for {len(bm25_scores)} chunks.")

Calculated BM25 scores for 47 chunks.

In [81]:
# ============================================================
# Top BM25 Results
# ============================================================

import numpy as np

top_indices = np.argsort(bm25_scores)[::-1][:10]

bm25_results = []

for idx in top_indices:
    bm25_results.append(
        (
            chunked_documents[idx],
            bm25_scores[idx]
        )
    )

print(f"Retrieved {len(bm25_results)} BM25 results.")

Retrieved 10 BM25 results.

In [82]:
for rank, (doc, score) in enumerate(bm25_results, start=1):

    print("=" * 80)
    print(f"Rank        : {rank}")
    print(f"Resume      : {doc.metadata['resume_name']}")
    print(f"BM25 Score  : {score:.2f}")

    print("\nPreview:\n")
    print(doc.page_content[:400])

================================================================================
Rank        : 1
Resume      : emily_davis
BM25 Score  : 87.63

Preview:

EMILY DAVIS
Email: emily.davis@cloudworks.io | Phone: +1-555-0104
Location: Austin, TX

PROFESSIONAL SUMMARY
Senior DevOps & Cloud Architect with 8 years of experience building resilient AWS &
Kubernetes infrastructure.

TECHNICAL SKILLS
Terraform, Kubernetes, Docker, AWS, Python, Bash, Ansible, Prometheus, Grafana, Jenkins,
GitLab CI, ArgoCD

EDUCATION
Bachelor of Science in Computer
================================================================================
Rank        : 2
Resume      : sophia_taylor
BM25 Score  : 33.44

Preview:

SOPHIA TAYLOR
Email: sophia.taylor@pmhub.com | Phone: +1-555-0106
Location: New York, NY

PROFESSIONAL SUMMARY
Principal Technical Product Manager with 7 years leading AI product lifecycle from inception
to GTM.

TECHNICAL SKILLS
Product Strategy, Agile/Scrum, A/B Testing, SQL, User Analytics, Jira, Figma, Roadmap
Planning, LLM Evaluation, Go-To-Market

EDUCATION
MBA, Columbia Busines
================================================================================
Rank        : 3
Resume      : marcus_lewis
BM25 Score  : 31.57

Preview:

MARCUS LEWIS
Email: marcus.lewis18@example.com | Phone: +1-555-0118
Location: San Francisco, CA

PROFESSIONAL SUMMARY
Experienced DevOps Engineer with 10 years of hands-on industry experience building
scalable systems and data products.

TECHNICAL SKILLS
Docker, Kubernetes, Terraform, AWS, CI/CD, Python, Bash, Prometheus, ArgoCD, REST APIs,
Unit Testing, Linux

EDUCATION
Bachelor of S
================================================================================
Rank        : 4
Resume      : sarah_jenkins
BM25 Score  : 28.73

Preview:

SARAH JENKINS
Email: sarah.j@securitysec.org | Phone: +1-555-0108
Location: Washington, DC

PROFESSIONAL SUMMARY
Cybersecurity Lead & SecOps Engineer with 8 years of experience in cloud security, threat
hunting, and compliance.

TECHNICAL SKILLS
Cybersecurity, SIEM, Splunk, Python, Bash, AWS Security, Penetration Testing, ISO 27001,
SOC2, IAM, Wireshark

EDUCATION
Master of Science in
================================================================================
Rank        : 5
Resume      : alice_smith
BM25 Score  : 24.94

Preview:

ALICE SMITH
Email: alice.smith@devmail.com | Phone: +1-555-0102
Location: Seattle, WA

PROFESSIONAL SUMMARY
Staff Full Stack Engineer with 9 years of experience designing scalable web applications and
cloud architectures.

TECHNICAL SKILLS
Python, TypeScript, React, Node.js, Django, FastAPI, PostgreSQL, Redis, AWS, GraphQL,
Docker, CI/CD, System Design

EDUCATION
Bachelor of Science i
================================================================================
Rank        : 6
Resume      : david_wilson
BM25 Score  : 22.98

Preview:

DAVID WILSON
Email: david.wilson@frontend.dev | Phone: +1-555-0107
Location: Remote / Denver, CO

PROFESSIONAL SUMMARY
Senior Frontend Engineer with 6 years of expertise building high-performance React and
Next.js web applications.

TECHNICAL SKILLS
React, Next.js, TypeScript, JavaScript, HTML5, CSS3, Tailwind CSS, Redux, GraphQL, Web
Vitals, Jest, Cypress

EDUCATION
Bachelor of Arts
================================================================================
Rank        : 7
Resume      : daniel_clark
BM25 Score  : 21.12

Preview:

DANIEL CLARK
Email: daniel.clark34@example.com | Phone: +1-555-0134
Location: Austin, TX

PROFESSIONAL SUMMARY
Experienced Data Engineer with 11 years of hands-on industry experience building scalable
systems and data products.

TECHNICAL SKILLS
Python, SQL, Apache Spark, Airflow, Snowflake, Kafka, dbt, AWS Redshift, Docker, CI/CD,
Agile, Linux

EDUCATION
Bachelor of Science in Comput
================================================================================
Rank        : 8
Resume      : alex_green
BM25 Score  : 20.37

Preview:

ALEX GREEN
Email: alex.green14@example.com | Phone: +1-555-0114
Location: Austin, TX

PROFESSIONAL SUMMARY
Experienced Backend Engineer with 9 years of hands-on industry experience building
scalable systems and data products.

TECHNICAL SKILLS
Python, FastAPI, Django, PostgreSQL, Redis, Docker, AWS, GraphQL, Microservices, Linux,
Unit Testing, REST APIs

EDUCATION
Bachelor of Science
================================================================================
Rank        : 9
Resume      : chloe_harris
BM25 Score  : 19.10

Preview:

CHLOE HARRIS
Email: chloe.harris22@example.com | Phone: +1-555-0122
Location: Austin, TX

PROFESSIONAL SUMMARY
Experienced Frontend Developer with 11 years of hands-on industry experience building
scalable systems and data products.

TECHNICAL SKILLS
React, TypeScript, Next.js, JavaScript, HTML5, CSS3, Tailwind, Redux, Jest, CI/CD, Jira, Agile

EDUCATION
Bachelor of Science in Computer
================================================================================
Rank        : 10
Resume      : chloe_hill
BM25 Score  : 18.87

Preview:

CHLOE HILL
Email: chloe.hill19@example.com | Phone: +1-555-0119
Location: Remote

PROFESSIONAL SUMMARY
Experienced Data Engineer with 5 years of hands-on industry experience building scalable
systems and data products.

TECHNICAL SKILLS
Python, SQL, Apache Spark, Airflow, Snowflake, Kafka, dbt, AWS Redshift, Docker, Linux, Unit
Testing, Agile

EDUCATION
Bachelor of Science in Computer

# Aggregate Resume Chunks by Candidate

Both semantic search and BM25 search return **individual resume chunks**.

However, recruiters evaluate **candidates**, not isolated sections of their resumes.

Therefore, we aggregate all retrieved chunks belonging to the same candidate.

For each candidate, we retain:

- Candidate Name
- Resume Path
- Semantic Similarity Score
- BM25 Keyword Score
- Relevant Resume Excerpts

This aggregated representation forms the basis for the final candidate ranking.

In [83]:
from collections import defaultdict

candidate_results = defaultdict(
    lambda: {
        "resume_name": "",
        "resume_path": "",
        "semantic_score": 0,
        "bm25_score": 0,
        "chunks": []
    }
)

for document, score in semantic_results:

    resume_name = document.metadata["resume_name"]

    candidate_results[resume_name]["resume_name"] = resume_name

    candidate_results[resume_name]["resume_path"] = document.metadata["resume_path"]

    # Keep the highest semantic similarity score
    candidate_results[resume_name]["semantic_score"] = max(
        candidate_results[resume_name]["semantic_score"],
        score
    )

    candidate_results[resume_name]["chunks"].append(
        document.page_content
    )

print(f"Candidates Retrieved : {len(candidate_results)}")

Candidates Retrieved : 10

In [84]:
for document, score in bm25_results:

    resume_name = document.metadata["resume_name"]

    if resume_name in candidate_results:

        candidate_results[resume_name]["bm25_score"] = max(
            candidate_results[resume_name]["bm25_score"],
            score
        )

In [85]:
first_candidate = next(iter(candidate_results.values()))

print(first_candidate["resume_name"])

print(first_candidate["semantic_score"])

print(first_candidate["bm25_score"])

print("\nNumber of Relevant Chunks")

print(len(first_candidate["chunks"]))

emily_davis
0.3658221662044525
87.62617055350826

Number of Relevant Chunks
1

# Candidate Ranking and Match Scoring

The retrieved candidates are ranked using a weighted scoring mechanism that combines multiple signals.

Since semantic similarity and BM25 scores are measured on different scales, both scores are first normalized to a common range before calculating the final match score.

### Scoring Components

- **Semantic Similarity (60%)**
  Measures how closely the resume content matches the overall meaning of the job description.

- **Keyword Matching (40%)**
  Rewards resumes containing important technologies, programming languages, frameworks, and domain-specific keywords.

The final score is scaled to a **0–100** range for easier interpretation.

In [86]:
import pandas as pd

ranking_df = pd.DataFrame(candidate_results.values())

ranking_df.head()

,resume_name,resume_path,semantic_score,bm25_score,chunks
0,emily_davis,d:\GitHub\RAG-Based-Profile-matching\data\resu...,0.365822,87.626171,[EMILY DAVIS \nEmail: emily.davis@cloudworks.i...
1,marcus_lewis,d:\GitHub\RAG-Based-Profile-matching\data\resu...,0.493865,31.574019,[MARCUS LEWIS \nEmail: marcus.lewis18@example....
2,kevin_allen,d:\GitHub\RAG-Based-Profile-matching\data\resu...,0.708492,0.000000,[KEVIN ALLEN \nEmail: kevin.allen27@example.co...
3,justin_lee,d:\GitHub\RAG-Based-Profile-matching\data\resu...,0.740842,0.000000,[JUSTIN LEE \nEmail: justin.lee26@example.com ...
4,alex_green,d:\GitHub\RAG-Based-Profile-matching\data\resu...,0.758024,20.370474,[ALEX GREEN \nEmail: alex.green14@example.com ...

In [87]:
# Normalize Semantic Score
semantic_min = ranking_df["semantic_score"].min()
semantic_max = ranking_df["semantic_score"].max()

ranking_df["semantic_norm"] = (
    (ranking_df["semantic_score"] - semantic_min)
    /
    (semantic_max - semantic_min + 1e-9)
)

# Normalize BM25 Score
bm25_min = ranking_df["bm25_score"].min()
bm25_max = ranking_df["bm25_score"].max()

ranking_df["bm25_norm"] = (
    (ranking_df["bm25_score"] - bm25_min)
    /
    (bm25_max - bm25_min + 1e-9)
)

In [89]:
# Compute Final Match Score
ranking_df["match_score"] = (
    0.60 * ranking_df["semantic_norm"]
    +
    0.40 * ranking_df["bm25_norm"]
) * 100

ranking_df["match_score"] = ranking_df["match_score"].round(2)

In [90]:
# Sort Candidates
ranking_df = ranking_df.sort_values(
    by="match_score",
    ascending=False
).reset_index(drop=True)

ranking_df[
    [
        "resume_name",
        "semantic_score",
        "bm25_score",
        "match_score"
    ]
]

        resume_name  semantic_score  bm25_score  match_score
0      daniel_clark        0.792291   21.119768        68.95
1        alex_green        0.758024   20.370474        63.84
2       ethan_young        0.797292    0.000000        60.00
3       elena_lewis        0.785591    0.000000        58.37
4  christopher_hall        0.773874    0.000000        56.74
5        laura_hill        0.768858    0.000000        56.05
6        justin_lee        0.740842    0.000000        52.15
7       kevin_allen        0.708492    0.000000        47.65
8       emily_davis        0.365822   87.626171        40.00
9      marcus_lewis        0.493865   31.574019        32.22

In [91]:
ranking_df["semantic_score"] = 1 / (1 + ranking_df["semantic_score"])

In [92]:
semantic_results[0][1]

0.3658221662044525

# Generate Match Reasoning

After ranking the candidates, the system generates a human-readable explanation describing why each candidate matches the job description.

The Large Language Model analyzes:

- The job description
- Candidate metadata
- Relevant resume excerpts
- Match score

It then summarizes the strengths of each candidate, highlighting matching skills, experience, and qualifications.

These explanations improve transparency and help recruiters understand the ranking results.

In [93]:
from langchain_core.prompts import ChatPromptTemplate

reasoning_prompt = ChatPromptTemplate.from_template("""
You are an expert technical recruiter.

Job Description:
{job_description}

Candidate Name:
{candidate_name}

Match Score:
{match_score}

Resume Excerpts:
{resume_excerpt}

Provide:

1. Matching Skills
2. Matching Experience
3. Strengths
4. Missing Skills (if any)
5. A concise reasoning in 3-4 sentences.

Return ONLY valid JSON.

{{
    "matched_skills": [],
    "missing_skills": [],
    "reasoning": ""
}}
""")

In [94]:
import json

candidate_reasoning = []

TOP_RESULTS = 10

for _, candidate in ranking_df.head(TOP_RESULTS).iterrows():

    excerpt = "\n\n".join(candidate["chunks"][:3])

    prompt = reasoning_prompt.format_messages(
        job_description=job_description,
        candidate_name=candidate["resume_name"],
        match_score=candidate["match_score"],
        resume_excerpt=excerpt
    )

    response = llm.invoke(prompt)

    try:
        result = json.loads(
            response.content.replace("```json", "").replace("```", "").strip()
        )

    except Exception:

        result = {
            "matched_skills": [],
            "missing_skills": [],
            "reasoning": response.content
        }

    result["resume_name"] = candidate["resume_name"]
    result["resume_path"] = candidate["resume_path"]
    result["match_score"] = candidate["match_score"]

    candidate_reasoning.append(result)

print("✅ Match reasoning generated.")

✅ Match reasoning generated.

In [95]:
candidate_reasoning[0]

{'matched_skills': [],
 'missing_skills': [],
 'reasoning': '```json\n{\n    "matched_skills": [\n        "Python",\n        "Docker",\n        "CI/CD",\n        "AWS"\n    ],\n    "missing_skills": [\n        "Terraform",\n        "Ansible",\n        "Kubernetes",\n        "Infrastructure as Code (IaC)",\n        "Advanced scripting in Bash",\n        "GitOps experience",\n        "AWS Solutions Architect certification",\n        "CKA certification"\n    ],\n    "reasoning": "Daniel Clark has a solid foundation in Python, Docker, and CI/CD, which are relevant to the DevOps role. However, he lacks critical skills such as Terraform, Ansible, and Kubernetes experience, which are essential for the position. Additionally, he does not have the required',
 'resume_name': 'daniel_clark',
 'resume_path': 'd:\\GitHub\\RAG-Based-Profile-matching\\data\\resumes\\daniel_clark.pdf',
 'match_score': 68.95}

#  Generate the Final Job Matching Results

The final stage of the Resume RAG pipeline is to generate a structured JSON response containing the ranked candidates.

The output follows the assignment specification and includes:

- Job Description
- Candidate Name
- Resume Path
- Match Score (0–100)
- Matched Skills
- Relevant Resume Excerpts
- Match Reasoning

This JSON can be easily consumed by downstream applications such as Applicant Tracking Systems (ATS), HR dashboards, or recruitment portals.

In [96]:
# ============================================================
# Generate Final Output
# ============================================================

final_output = {
    "job_description": job_description,
    "top_matches": []
}

for candidate in candidate_reasoning:

    # Find candidate details
    row = ranking_df[
        ranking_df["resume_name"] == candidate["resume_name"]
    ].iloc[0]

    final_output["top_matches"].append({

        "candidate_name": candidate["resume_name"],

        "resume_path": candidate["resume_path"],

        "match_score": round(candidate["match_score"], 2),

        "matched_skills": candidate["matched_skills"],

        "relevant_excerpts": row["chunks"][:2],

        "reasoning": candidate["reasoning"]

    })

In [97]:
import json

print(
    json.dumps(
        final_output,
        indent=4
    )
)

{
    "job_description": "JOB TITLE: Senior DevOps & Cloud Architect\nLOCATION: Austin, TX / Remote\nEXPERIENCE REQUIRED: 6+ years\n\nJOB DESCRIPTION:\nJoin our cloud operations team to build scalable, automated Infrastructure-as-Code. You will manage multi-region Kubernetes clusters on AWS, automate CI/CD pipelines, and monitor telemetry with Prometheus/Grafana.\n\nMUST-HAVE REQUIREMENTS:\n- 6+ years of DevOps / Infrastructure experience.\n- Mastery of Terraform, Ansible, and Infrastructure as Code (IaC).\n- Heavy hands-on experience with Kubernetes (EKS/GKE) and Docker.\n- Advanced scripting in Python or Bash.\n- Deep AWS expertise (VPC, IAM, EKS, EC2).\n\nNICE-TO-HAVE SKILLS:\n- GitOps experience with ArgoCD or Flux.\n- Certified AWS Solutions Architect or CKA certification.\n",
    "top_matches": [
        {
            "candidate_name": "daniel_clark",
            "resume_path": "d:\\GitHub\\RAG-Based-Profile-matching\\data\\resumes\\daniel_clark.pdf",
            "match_score": 68.95,
            "matched_skills": [],
            "relevant_excerpts": [
                "DANIEL CLARK \nEmail: daniel.clark34@example.com | Phone: +1-555-0134 \nLocation: Austin, TX \n \nPROFESSIONAL SUMMARY \nExperienced Data Engineer with 11 years of hands-on industry experience building scalable \nsystems and data products. \n \nTECHNICAL SKILLS \nPython, SQL, Apache Spark, Airflow, Snowflake, Kafka, dbt, AWS Redshift, Docker, CI/CD, \nAgile, Linux \n \nEDUCATION \nBachelor of Science in Computer Science, University of Texas at Austin (2013) \n \nPROFESSIONAL EXPERIENCE \nSenior Data Engineer | Tech Company E | 2020 \u2013 Present (4 years) \n\u2022 Spearheaded key initiatives for data engineer domain improving system efficiency by 32%. \n\u2022 Utilized Python, SQL, Apache Spark, Airflow to build scalable production workflows. \n\u2022 Collaborated across multi-functional teams to deliver reliable enterprise solutions. \n \nData Engineer | Software Solutions O | 2013 \u2013 2020 (7 years) \n\u2022 Developed core platform features using Python and SQL. \n\u2022 Maintained automated test coverage and documentation."
            ],
            "reasoning": "```json\n{\n    \"matched_skills\": [\n        \"Python\",\n        \"Docker\",\n        \"CI/CD\",\n        \"AWS\"\n    ],\n    \"missing_skills\": [\n        \"Terraform\",\n        \"Ansible\",\n        \"Kubernetes\",\n        \"Infrastructure as Code (IaC)\",\n        \"Advanced scripting in Bash\",\n        \"GitOps experience\",\n        \"AWS Solutions Architect certification\",\n        \"CKA certification\"\n    ],\n    \"reasoning\": \"Daniel Clark has a solid foundation in Python, Docker, and CI/CD, which are relevant to the DevOps role. However, he lacks critical skills such as Terraform, Ansible, and Kubernetes experience, which are essential for the position. Additionally, he does not have the required"
        },
        {
            "candidate_name": "alex_green",
            "resume_path": "d:\\GitHub\\RAG-Based-Profile-matching\\data\\resumes\\alex_green.pdf",
            "match_score": 63.84,
            "matched_skills": [],
            "relevant_excerpts": [
                "ALEX GREEN \nEmail: alex.green14@example.com | Phone: +1-555-0114 \nLocation: Austin, TX \n \nPROFESSIONAL SUMMARY \nExperienced Backend Engineer with 9 years of hands-on industry experience building \nscalable systems and data products. \n \nTECHNICAL SKILLS \nPython, FastAPI, Django, PostgreSQL, Redis, Docker, AWS, GraphQL, Microservices, Linux, \nUnit Testing, REST APIs \n \nEDUCATION \nBachelor of Science in Computer Science, UC San Diego (2015) \n \nPROFESSIONAL EXPERIENCE \nSenior Backend Engineer | Tech Company E | 2020 \u2013 Present (4 years) \n\u2022 Spearheaded key initiatives for backend engineer domain improving system efficiency by \n18%. \n\u2022 Utilized Python, FastAPI, Django, PostgreSQL to build scalable production workflows. \n\u2022 Collaborated across multi-functional teams to deliver reliable enterprise solutions. \n \nBackend Engineer | Software Solutions O | 2015 \u2013 2020 (5 years) \n\u2022 Developed core platform features using Python and FastAPI. \n\u2022 Maintained automated test coverage and documentation."
            ],
            "reasoning": "```json\n{\n    \"matched_skills\": [\n        \"Python\",\n        \"Docker\",\n        \"AWS\"\n    ],\n    \"missing_skills\": [\n        \"DevOps / Infrastructure experience\",\n        \"Terraform\",\n        \"Ansible\",\n        \"Kubernetes (EKS/GKE)\",\n        \"CI/CD pipelines\",\n        \"Prometheus/Grafana\",\n        \"GitOps experience\",\n        \"AWS Solutions Architect or CKA certification\"\n    ],\n    \"reasoning\": \"While Alex has a solid background in backend engineering with experience in Python, Docker, and AWS, he lacks the specific DevOps and Infrastructure experience required for the role. Key skills such as Terraform, Ansible, Kubernetes, and CI/CD automation are missing, which are"
        },
        {
            "candidate_name": "ethan_young",
            "resume_path": "d:\\GitHub\\RAG-Based-Profile-matching\\data\\resumes\\ethan_young.pdf",
            "match_score": 60.0,
            "matched_skills": [],
            "relevant_excerpts": [
                "ETHAN YOUNG \nEmail: ethan.young12@example.com | Phone: +1-555-0112 \nLocation: Seattle, WA \n \nPROFESSIONAL SUMMARY \nExperienced Data Engineer with 9 years of hands-on industry experience building scalable \nsystems and data products. \n \nTECHNICAL SKILLS \nPython, SQL, Apache Spark, Airflow, Snowflake, Kafka, dbt, AWS Redshift, Docker, Git, Linux, \nCI/CD \n \nEDUCATION \nBachelor of Science in Computer Science, Carnegie Mellon University (2015) \n \nPROFESSIONAL EXPERIENCE \nSenior Data Engineer | Tech Company C | 2020 \u2013 Present (4 years) \n\u2022 Spearheaded key initiatives for data engineer domain improving system efficiency by 31%. \n\u2022 Utilized Python, SQL, Apache Spark, Airflow to build scalable production workflows. \n\u2022 Collaborated across multi-functional teams to deliver reliable enterprise solutions. \n \nData Engineer | Software Solutions M | 2015 \u2013 2020 (5 years) \n\u2022 Developed core platform features using Python and SQL. \n\u2022 Maintained automated test coverage and documentation."
            ],
            "reasoning": "```json\n{\n    \"matched_skills\": [\n        \"Python\",\n        \"Docker\",\n        \"AWS\"\n    ],\n    \"missing_skills\": [\n        \"DevOps / Infrastructure experience\",\n        \"Terraform\",\n        \"Ansible\",\n        \"Kubernetes (EKS/GKE)\",\n        \"CI/CD automation\",\n        \"Prometheus/Grafana\",\n        \"GitOps (ArgoCD or Flux)\",\n        \"AWS Solutions Architect or CKA certification\"\n    ],\n    \"reasoning\": \"Ethan Young has a strong background in data engineering with relevant skills in Python, Docker, and AWS. However, he lacks the specific DevOps and Infrastructure experience required for the role, as well as mastery in Terraform, Ansible, and"
        },
        {
            "candidate_name": "elena_lewis",
            "resume_path": "d:\\GitHub\\RAG-Based-Profile-matching\\data\\resumes\\elena_lewis.pdf",
            "match_score": 58.37,
            "matched_skills": [],
            "relevant_excerpts": [
                "ELENA LEWIS \nEmail: elena.lewis15@example.com | Phone: +1-555-0115 \nLocation: Chicago, IL \n \nPROFESSIONAL SUMMARY \nExperienced Data Engineer with 8 years of hands-on industry experience building scalable \nsystems and data products. \n \nTECHNICAL SKILLS \nPython, SQL, Apache Spark, Airflow, Snowflake, Kafka, dbt, AWS Redshift, Docker, REST APIs, \nGit, Agile \n \nEDUCATION \nBachelor of Science in Computer Science, UC San Diego (2016) \n \nPROFESSIONAL EXPERIENCE \nSenior Data Engineer | Tech Company F | 2020 \u2013 Present (4 years) \n\u2022 Spearheaded key initiatives for data engineer domain improving system efficiency by 32%. \n\u2022 Utilized Python, SQL, Apache Spark, Airflow to build scalable production workflows. \n\u2022 Collaborated across multi-functional teams to deliver reliable enterprise solutions. \n \nData Engineer | Software Solutions P | 2016 \u2013 2020 (4 years) \n\u2022 Developed core platform features using Python and SQL. \n\u2022 Maintained automated test coverage and documentation."
            ],
            "reasoning": "```json\n{\n    \"matched_skills\": [\n        \"Python\",\n        \"Docker\",\n        \"AWS\"\n    ],\n    \"missing_skills\": [\n        \"DevOps / Infrastructure experience\",\n        \"Terraform\",\n        \"Ansible\",\n        \"Kubernetes (EKS/GKE)\",\n        \"CI/CD pipelines\",\n        \"Prometheus\",\n        \"Grafana\",\n        \"GitOps experience\",\n        \"AWS Solutions Architect or CKA certification\"\n    ],\n    \"reasoning\": \"Elena Lewis has a solid background in Python and Docker, along with some AWS experience, but lacks the specific DevOps and Infrastructure skills required for the role. Key areas such as Terraform, Kubernetes, and CI/CD automation are missing from her experience, which"
        },
        {
            "candidate_name": "christopher_hall",
            "resume_path": "d:\\GitHub\\RAG-Based-Profile-matching\\data\\resumes\\christopher_hall.pdf",
            "match_score": 56.74,
            "matched_skills": [],
            "relevant_excerpts": [
                "CHRISTOPHER HALL \nEmail: christopher.hall30@example.com | Phone: +1-555-0130 \nLocation: Boston, MA \n \nPROFESSIONAL SUMMARY \nExperienced Backend Engineer with 7 years of hands-on industry experience building \nscalable systems and data products. \n \nTECHNICAL SKILLS \nPython, FastAPI, Django, PostgreSQL, Redis, Docker, AWS, GraphQL, Microservices, Jira, \nAgile, Linux \n \nEDUCATION \nBachelor of Science in Computer Science, University of Southern California (2017) \n \nPROFESSIONAL EXPERIENCE \nSenior Backend Engineer | Tech Company A | 2020 \u2013 Present (4 years) \n\u2022 Spearheaded key initiatives for backend engineer domain improving system efficiency by \n44%. \n\u2022 Utilized Python, FastAPI, Django, PostgreSQL to build scalable production workflows. \n\u2022 Collaborated across multi-functional teams to deliver reliable enterprise solutions. \n \nBackend Engineer | Software Solutions K | 2017 \u2013 2020 (3 years) \n\u2022 Developed core platform features using Python and FastAPI."
            ],
            "reasoning": "```json\n{\n    \"matched_skills\": [\n        \"Python\",\n        \"Docker\",\n        \"AWS\"\n    ],\n    \"missing_skills\": [\n        \"Terraform\",\n        \"Ansible\",\n        \"Infrastructure as Code (IaC)\",\n        \"Kubernetes (EKS/GKE)\",\n        \"CI/CD pipelines\",\n        \"Prometheus\",\n        \"Grafana\",\n        \"GitOps (ArgoCD or Flux)\",\n        \"AWS Solutions Architect or CKA certification\"\n    ],\n    \"reasoning\": \"Christopher Hall has a solid foundation in backend engineering with experience in Python, Docker, and AWS, which are relevant to the DevOps role. However, he lacks critical skills such as Terraform, Ansible, and Kubernetes, which"
        },
        {
            "candidate_name": "laura_hill",
            "resume_path": "d:\\GitHub\\RAG-Based-Profile-matching\\data\\resumes\\laura_hill.pdf",
            "match_score": 56.05,
            "matched_skills": [],
            "relevant_excerpts": [
                "LAURA HILL \nEmail: laura.hill17@example.com | Phone: +1-555-0117 \nLocation: Boston, MA \n \nPROFESSIONAL SUMMARY \nExperienced Data Engineer with 3 years of hands-on industry experience building scalable \nsystems and data products. \n \nTECHNICAL SKILLS \nPython, SQL, Apache Spark, Airflow, Snowflake, Kafka, dbt, AWS Redshift, Docker, REST APIs, \nGit, Linux \n \nEDUCATION \nBachelor of Science in Computer Science, University of Texas at Austin (2021) \n \nPROFESSIONAL EXPERIENCE \nSenior Data Engineer | Tech Company H | 2020 \u2013 Present (4 years) \n\u2022 Spearheaded key initiatives for data engineer domain improving system efficiency by 42%. \n\u2022 Utilized Python, SQL, Apache Spark, Airflow to build scalable production workflows. \n\u2022 Collaborated across multi-functional teams to deliver reliable enterprise solutions. \n \nData Engineer | Software Solutions R | 2021 \u2013 2020 (-1 years) \n\u2022 Developed core platform features using Python and SQL. \n\u2022 Maintained automated test coverage and documentation."
            ],
            "reasoning": "{\n    \"matched_skills\": [\n        \"Python\",\n        \"Docker\",\n        \"AWS\"\n    ],\n    \"missing_skills\": [\n        \"DevOps / Infrastructure experience\",\n        \"Terraform\",\n        \"Ansible\",\n        \"Kubernetes (EKS/GKE)\",\n        \"CI/CD pipelines\",\n        \"Prometheus/Grafana\",\n        \"GitOps experience\",\n        \"AWS Solutions Architect or CKA certification\"\n    ],\n    \"reasoning\": \"Laura Hill has a background in data engineering with experience in Python, Docker, and AWS, which are relevant to the DevOps role. However, she lacks the required 6+ years of DevOps experience, mastery of Terraform and Ansible, and hands-on experience with Kubernetes and"
        },
        {
            "candidate_name": "justin_lee",
            "resume_path": "d:\\GitHub\\RAG-Based-Profile-matching\\data\\resumes\\justin_lee.pdf",
            "match_score": 52.15,
            "matched_skills": [],
            "relevant_excerpts": [
                "JUSTIN LEE \nEmail: justin.lee26@example.com | Phone: +1-555-0126 \nLocation: Remote \n \nPROFESSIONAL SUMMARY \nExperienced Backend Engineer with 10 years of hands-on industry experience building \nscalable systems and data products. \n \nTECHNICAL SKILLS \nPython, FastAPI, Django, PostgreSQL, Redis, Docker, AWS, GraphQL, Microservices, CI/CD, \nREST APIs, Jira \n \nEDUCATION \nBachelor of Science in Computer Science, Carnegie Mellon University (2014) \n \nPROFESSIONAL EXPERIENCE \nSenior Backend Engineer | Tech Company G | 2020 \u2013 Present (4 years) \n\u2022 Spearheaded key initiatives for backend engineer domain improving system efficiency by \n39%. \n\u2022 Utilized Python, FastAPI, Django, PostgreSQL to build scalable production workflows. \n\u2022 Collaborated across multi-functional teams to deliver reliable enterprise solutions. \n \nBackend Engineer | Software Solutions Q | 2014 \u2013 2020 (6 years) \n\u2022 Developed core platform features using Python and FastAPI. \n\u2022 Maintained automated test coverage and documentation."
            ],
            "reasoning": "```json\n{\n    \"matched_skills\": [\n        \"Python\",\n        \"Docker\",\n        \"AWS\"\n    ],\n    \"missing_skills\": [\n        \"DevOps / Infrastructure experience\",\n        \"Terraform\",\n        \"Ansible\",\n        \"Infrastructure as Code (IaC)\",\n        \"Kubernetes (EKS/GKE)\",\n        \"CI/CD pipelines\",\n        \"Prometheus\",\n        \"Grafana\",\n        \"GitOps experience\",\n        \"ArgoCD\",\n        \"Flux\",\n        \"AWS Solutions Architect certification\",\n        \"CKA certification\"\n    ],\n    \"reasoning\": \"Justin Lee has a solid foundation in Python, Docker, and AWS, which are relevant to the role. However, he lacks the required DevOps"
        },
        {
            "candidate_name": "kevin_allen",
            "resume_path": "d:\\GitHub\\RAG-Based-Profile-matching\\data\\resumes\\kevin_allen.pdf",
            "match_score": 47.65,
            "matched_skills": [],
            "relevant_excerpts": [
                "KEVIN ALLEN \nEmail: kevin.allen27@example.com | Phone: +1-555-0127 \nLocation: Chicago, IL \n \nPROFESSIONAL SUMMARY \nExperienced Data Engineer with 7 years of hands-on industry experience building scalable \nsystems and data products. \n \nTECHNICAL SKILLS \nPython, SQL, Apache Spark, Airflow, Snowflake, Kafka, dbt, AWS Redshift, Docker, Linux, Unit \nTesting, REST APIs \n \nEDUCATION \nBachelor of Science in Computer Science, University of Southern California (2017) \n \nPROFESSIONAL EXPERIENCE \nSenior Data Engineer | Tech Company H | 2020 \u2013 Present (4 years) \n\u2022 Spearheaded key initiatives for data engineer domain improving system efficiency by 39%. \n\u2022 Utilized Python, SQL, Apache Spark, Airflow to build scalable production workflows. \n\u2022 Collaborated across multi-functional teams to deliver reliable enterprise solutions. \n \nData Engineer | Software Solutions R | 2017 \u2013 2020 (3 years) \n\u2022 Developed core platform features using Python and SQL. \n\u2022 Maintained automated test coverage and documentation."
            ],
            "reasoning": "```json\n{\n    \"matched_skills\": [\n        \"Python\",\n        \"Docker\",\n        \"AWS\"\n    ],\n    \"missing_skills\": [\n        \"DevOps / Infrastructure experience\",\n        \"Terraform\",\n        \"Ansible\",\n        \"Kubernetes (EKS/GKE)\",\n        \"CI/CD pipelines\",\n        \"Prometheus/Grafana\",\n        \"GitOps (ArgoCD or Flux)\",\n        \"AWS Solutions Architect or CKA certification\"\n    ],\n    \"reasoning\": \"Kevin Allen has a solid foundation in Python, Docker, and AWS, which are relevant to the Senior DevOps & Cloud Architect role. However, he lacks direct experience in key areas such as Terraform, Ansible, Kubernetes, and CI/CD"
        },
        {
            "candidate_name": "emily_davis",
            "resume_path": "d:\\GitHub\\RAG-Based-Profile-matching\\data\\resumes\\emily_davis.pdf",
            "match_score": 40.0,
            "matched_skills": [],
            "relevant_excerpts": [
                "EMILY DAVIS \nEmail: emily.davis@cloudworks.io | Phone: +1-555-0104 \nLocation: Austin, TX \n \nPROFESSIONAL SUMMARY \nSenior DevOps & Cloud Architect with 8 years of experience building resilient AWS & \nKubernetes infrastructure. \n \nTECHNICAL SKILLS \nTerraform, Kubernetes, Docker, AWS, Python, Bash, Ansible, Prometheus, Grafana, Jenkins, \nGitLab CI, ArgoCD \n \nEDUCATION \nBachelor of Science in Computer Information Systems, UT Austin (2016) \n \nPROFESSIONAL EXPERIENCE \nSenior DevOps Architect | SkyHigh Infrastructure | 2020 \u2013 Present (4 years) \n\u2022 Managed multi-region AWS EKS clusters hosting 300+ microservices. \n\u2022 Reduced cloud infrastructure cost by 35% through spot instances and automated auto-\nscaling. \n \nInfrastructure Engineer | DataPipe Cloud | 2016 \u2013 2020 (4 years) \n\u2022 Automated zero-downtime deployment pipelines with Terraform and GitOps (ArgoCD)."
            ],
            "reasoning": "```json\n{\n    \"matched_skills\": [\n        \"Terraform\",\n        \"Kubernetes\",\n        \"Docker\",\n        \"AWS\",\n        \"Python\",\n        \"Bash\",\n        \"Ansible\",\n        \"Prometheus\",\n        \"Grafana\",\n        \"ArgoCD\"\n    ],\n    \"missing_skills\": [\n        \"CI/CD pipeline automation experience\",\n        \"Deep AWS expertise (VPC, IAM, EKS, EC2)\"\n    ],\n    \"reasoning\": \"Emily Davis has a strong background in DevOps and cloud architecture with 8 years of experience and relevant technical skills that align well with the job description. However, the match score is low due to the lack of explicit mention of deep AWS expertise and CI"
        },
        {
            "candidate_name": "marcus_lewis",
            "resume_path": "d:\\GitHub\\RAG-Based-Profile-matching\\data\\resumes\\marcus_lewis.pdf",
            "match_score": 32.22,
            "matched_skills": [],
            "relevant_excerpts": [

In [98]:
# ============================================================
# Save Results
# ============================================================

output_file = OUTPUT_DIR / "job_matching_results.json"

with open(output_file, "w", encoding="utf-8") as file:

    json.dump(
        final_output,
        file,
        indent=4
    )

print(f"Results saved to:\n{output_file}")

Results saved to:
d:\GitHub\RAG-Based-Profile-matching\outputs\job_matching_results.json

# Performance Evaluation

To evaluate the effectiveness of the Resume RAG System, we measure several performance metrics.

### Metrics

- Number of Resume Documents
- Number of Resume Chunks
- Number of Indexed Embeddings
- Number of Retrieved Candidates
- Retrieval Latency
- Average Match Score

These metrics provide insight into the scalability and efficiency of the retrieval pipeline.

In [99]:
import time

start = time.perf_counter()

_ = vector_store.similarity_search(
    job_description,
    k=10
)

end = time.perf_counter()

latency = end - start

print("=" * 60)

print(f"Total Resumes        : {len(resume_files)}")

print(f"Total Chunks         : {len(chunked_documents)}")

print(f"Retrieved Candidates : {len(candidate_reasoning)}")

print(f"Retrieval Time       : {latency:.4f} seconds")

print(f"Average Match Score  : {ranking_df['match_score'].mean():.2f}")

print("=" * 60)

============================================================
Total Resumes        : 34
Total Chunks         : 47
Retrieved Candidates : 10
Retrieval Time       : 0.3671 seconds
Average Match Score  : 53.60
============================================================

# Conclusion

In this project, we implemented a complete Retrieval-Augmented Generation (RAG) system for intelligent resume screening and job matching.

## Key Features

- Loaded and processed resume PDF documents.
- Applied intelligent document chunking.
- Generated semantic embeddings.
- Indexed resume chunks using ChromaDB.
- Retrieved relevant resumes using semantic search.
- Enhanced retrieval using Hybrid Search (Semantic + BM25).
- Ranked candidates using a weighted scoring mechanism.
- Generated explainable match reasoning using a Large Language Model.
- Produced structured JSON output compatible with recruitment systems.

This implementation demonstrates how modern RAG architectures can improve recruitment workflows by combining semantic retrieval, keyword matching, and LLM-powered reasoning.